# Enable mouse support (scrolling, click to switch panel
set -g mouse on

# Enable colors
set -g default-terminal "screen-256color"

# Show highlight prefix
set -g status-right '#{prefix_highlight}'

# Allow longler session names
set -g status-left-length 42

# Lets tmux recognize modifier combinations—such as Ctrl + Shift,
# Shift + Enter, or specific function keys—that standard terminal
# encoding usually ignores or drops.
set -g extended-keys on
set -g extended-keys-format csi-u

# Bind to clear history
bind -n C-k clear-history
bind -n C-q kill-session

# Also clear history when press Ctr+L
bind -n C-l send-keys 'C-l' \; run-shell "sleep .1" \; clear-history

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'             # Copy to system clipboard
set -g @plugin 'tmux-plugins/tmux-sensible'         # Basic settings everyone can agree on
set -g @plugin 'alexanderjeurissen/sombre.tmux'     # Minial theme
set -g @plugin 'tmux-plugins/tmux-prefix-highlight' # Highlight the prefix (Cmd-B)

# Plugin's config
set -g @yank_selection_mouse 'clipboard'
set -g @yank_action 'copy-pipe'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
